### ISSUE TITLE
How to remove floating label text in Spinner 4 or Spinner 5

### ISSUE THREAD

**Issue by sylendra7** [akamud/MaterialSpinner-Xamarin#1]
How to remove floating label text in Spinner 4 or Spinner 5?
and how to change spinner bottom line color and text color?

**Comment by akamud** [comment]
The underline color can be changed using the `ms_baseColor` attribute.

The ability to remove the floating label text will come in the `1.1.1` release I'll be doing soon. I'll let you know when it's available, it shouldn't be longer than 24 hours.

**Comment by akamud** [comment]
The new version is now released: [Nuget](https://www.nuget.org/packages/MaterialSpinner-Xamarin/1.1.1)

You can now remove the floating label text with `app:ms_enableFloatingLabel="false"`. There are a few more notable features that are worth taking a look at the updated README.
